name: Provision infrastructure

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy to'
        default: staging
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ inputs.environment }}
  cancel-in-progress: false

jobs:
  pulumi:
    runs-on: self-hosted
    env:
      PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
      PULUMI_BACKEND_URL: s3://bn-digital/pulumi/${{ github.event.repository.name }}?endpoint=fra1.digitaloceanspaces.com
      AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Installing dependencies
        run: yarn workspaces focus @${{ github.event.repository.name }}/cloud

      - name: Preview infrastructure plan
        uses: pulumi/actions@v4
        with:
          command: preview
          work-dir: packages/cloud
          stack-name: ${{ inputs.environment }}
