name: Provision infrastructure

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy to'
        default: staging
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ inputs.environment }}
  cancel-in-progress: false

jobs:
  pulumi:
    runs-on: self-hosted
    env:
      PULUMI_BACKEND_URL: s3://bn-digital/pulumi/${{ github.event.repository.name }}?endpoint=fra1.digitaloceanspaces.com
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
      GITHUB_OWNER: ${{ github.repository_owner }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Read from Vault
        uses: hashicorp/vault-action@v2.5.0
        with:
          url: ${{ secrets.VAULT_ENDPOINT }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            infrastructure/data/pulumi            config-passphrase     | PULUMI_CONFIG_PASSPHRASE    ;
            infrastructure/data/vault             url                   | VAULT_SERVER_URL            ;
            infrastructure/data/vault             url                   | VAULT_ADDR                  ;
            infrastructure/data/vault             pulumi-token          | VAULT_TOKEN                 ;
            infrastructure/data/registry          endpoint              | HARBOR_URL                  ;
            infrastructure/data/registry          admin-username        | HARBOR_USERNAME             ;
            infrastructure/data/registry          admin-password        | HARBOR_PASSWORD             ;
            infrastructure/data/postgresql        host                  | PGHOST                      ;
            infrastructure/data/postgresql        username              | PGUSER                      ;
            infrastructure/data/postgresql        password              | PGPASS                      ;
            infrastructure/data/postgresql        ssl-mode              | PGSSLMODE                   ;
            infrastructure/data/digitalocean      token                 | DIGITALOCEAN_TOKEN          ;
            infrastructure/data/spaces            access-key-id         | AWS_ACCESS_KEY_ID           ;
            infrastructure/data/spaces            secret-access-key     | AWS_SECRET_ACCESS_KEY       ;
            infrastructure/data/spaces            access-key-id         | SPACES_ACCESS_KEY_ID        ;
            infrastructure/data/spaces            secret-access-key     | SPACES_SECRET_ACCESS_KEY    ;

      - name: Installing dependencies
        env:
          YARN_NM_HOISTING_LIMITS: workspaces
        run: yarn workspaces focus @${{ github.event.repository.name }}/cloud --production

      - name: Preview infrastructure plan
        uses: pulumi/actions@v4
        with:
          command: preview
          work-dir: packages/cloud
          stack-name: ${{ inputs.environment }}
