name: Provision infrastructure

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy to'
        default: staging
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ inputs.environment }}
  cancel-in-progress: false

jobs:
  pulumi:
    runs-on: self-hosted
    env:
      PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
      PULUMI_BACKEND_URL: s3://bn-digital/pulumi/${{ github.repository }}?endpoint=fra1.digitaloceanspaces.com
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.SPACES_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SPACES_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Installing dependencies
        run: yarn workspaces focus @${{ github.event.repository.name }}/cloud

      - name: Preview infrastructure plan
        uses: pulumi/actions@v4
        with:
          command: preview
          work-dir: packages/cloud
          stack-name: ${{ inputs.environment }}
